hal/testsuite.next

- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/datasource/DataSourceCreateTest.java
See https://issues.jboss.org/browse/HAL-1440
> HAL-1440 related fixes in DataSourceCreateTest

- common/src/main/java/org/jboss/hal/testsuite/CrudConstants.java
- common/src/main/java/org/jboss/hal/testsuite/page/configuration/LoggingConfigurationPage.java
- common/src/main/java/org/jboss/hal/testsuite/page/configuration/LoggingProfileConfigurationPage.java
- common/src/main/java/org/jboss/hal/testsuite/page/configuration/LoggingSubsystemConfigurationPage.java
- pom.xml
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/JsonFormatterAbstractTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/LoggingFixtures.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/XmlFormatterAbstractTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/profile/JsonFormatterProfileTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/profile/XmlFormatterProfileTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/subsystem/JsonFormatterSubsystemTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/subsystem/XmlFormatterSubsystemTest.java
See https://issues.jboss.org/browse/HAL-1463
>  HAL-1463: Tests for JSON and XML log formatter configuration 

- pom.xml
- tests/pom.xml
See https://issues.apache.org/jira/browse/SUREFIRE-1439
> SUREFIRE-1439: upgrade surefire plugin version

- README.md
- common/src/main/java/org/jboss/hal/testsuite/Console.java
- common/src/main/java/org/jboss/hal/testsuite/creaper/ManagementClientProvider.java
- common/src/main/java/org/jboss/hal/testsuite/page/HomePage.java
- common/src/main/java/org/jboss/hal/testsuite/page/keycloak/KeycloakAccessControlPage.java
- common/src/main/java/org/jboss/hal/testsuite/page/keycloak/KeycloakLoginPage.java
- pom.xml
- tests/keycloak/README.md
- tests/keycloak/example-setup.sh
- tests/keycloak/pom.xml
- tests/keycloak/src/test/java/org/jboss/hal/testsuite/test/keycloak/KeycloakAuthenticationTest.java
- tests/keycloak/src/test/java/org/jboss/hal/testsuite/test/keycloak/KeycloakOperations.java
- tests/keycloak/src/test/java/org/jboss/hal/testsuite/test/keycloak/KeycloakWildflyOperations.java
- tests/pom.xml
Requires some README and probably more JavaDoc yet.
> Keycloak integration tests

- common/src/main/java/org/jboss/hal/testsuite/fragment/AlertFragment.java
- common/src/main/java/org/jboss/hal/testsuite/fragment/finder/FinderPreviewFragment.java
- common/src/main/java/org/jboss/hal/testsuite/fragment/finder/preview/MicroProfileHealthPreviewFragment.java
- tests/basic/pom.xml
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/systemproperty/SystemPropertyFixtures.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/systemproperty/SystemPropertyTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/runtime/microprofile/health/CustomHealthCheck.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/runtime/microprofile/health/MicroProfileHealthCheckTest.java
>  Test for microprofile custom health check 

- common/src/main/java/org/jboss/hal/testsuite/page/configuration/ElytronOtherSettingsPage.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/ElytronFixtures.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/other/settings/ssl/ServerSSLSNIContextTest.java
Upstream Issue: https://issues.jboss.org/browse/HAL-1557
EAP7 Issue: https://issues.jboss.org/browse/EAP7-1163
> Added tests for server-ssl-sni-context

- common/src/main/java/org/jboss/hal/testsuite/fragment/AlertFragment.java
- common/src/main/java/org/jboss/hal/testsuite/fragment/finder/FinderPreviewFragment.java
- common/src/main/java/org/jboss/hal/testsuite/page/configuration/ModclusterPage.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/modcluster/CustomLoadMetricTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/modcluster/LoadMetricTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/modcluster/ModclusterConfigurationTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/modcluster/ModclusterFixtures.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/modcluster/ModclusterLoadProviderDynamicTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/modcluster/ModclusterLoadProviderSimpleTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/modcluster/ProxyFinderTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/runtime/microprofile/health/MicroProfileHealthCheckTest.java
https://issues.jboss.org/browse/HAL-1504
> HAL-1504: Add tests for new modcluster resources

- tests/basic/src/test/java/org/jboss/hal/testsuite/test/runtime/MissingOperationsTestCase.java
Jira link [https://issues.jboss.org/browse/HAL-1582](https://issues.jboss.org/browse/HAL-1582)
Description:Console for domain mode has server-group missing some operations. It looks like Remove is missing as well as Copy.
> [HAL-1582] - Domain mode has server-group missing some operations

- common/src/main/java/org/jboss/hal/testsuite/fragment/FormFragment.java
This fixes flipping switch item (the DOM tree for switch has changed)
> Fix flipping switch items

- common/src/main/java/org/jboss/hal/testsuite/page/configuration/ElytronSecurityRealmsPage.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/ElytronFixtures.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/JDBCRealmTest.java
https://issues.jboss.org/browse/HAL-1609
> HAL-1609: Configure new / enhanced password mappers

- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/LoggingFixtures.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/SyslogHandlerAbstractTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/configuration/handler/syslog/handler/SyslogHandlerTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/logging/logging/profiles/handler/syslog/handler/SyslogHandlerTest.java
https://issues.jboss.org/browse/HAL-1601
> HAL-1601: Expose named-formatter attribute for syslog-handler

- tests/basic/src/test/java/org/jboss/hal/testsuite/test/runtime/io/UrlConnectionTestCase.java
Jira link [https://issues.jboss.org/browse/JBEAP-16671](https://issues.jboss.org/browse/JBEAP-16671)
Description:
See attached screenshot, it shows the URL which is not valid if you remove the http-interface and just have the https-interface
> [JBEAP-16671] - Console shows server URL as http://[host]:webPort even if http is disabled

- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/server/connections/connection/factory/ConnectionFactoryTest.java
- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/server/connections/pooled/connection/factory/PooledConnectionFactoryTest.java
https://issues.jboss.org/browse/HAL-1603
> HAL-1603: Add tests to configure messaging clusters behind http load balancers 

- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/remote/activemq/server/connection/factory/ConnectionFactoryTest.java
https://issues.jboss.org/browse/HAL-1608
> HAL-1608: Configure enable-amq1-prefix attribute

- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/infinispan/cache/container/CacheViewTest.java
[HAL-1627] - CacheView does not work
Description: When opening a cache the following error is shown:
Jira issue: [https://issues.redhat.com/browse/HAL-1627](https://issues.redhat.com/browse/HAL-1627)
PR to master [https://github.com/hal/testsuite.next/pull/135](https://github.com/hal/testsuite.next/pull/135)
> [HAL-1627] - CacheView does not work

- tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/datasource/XADataSourceConfigurationTest.java
A test-case for https://issues.redhat.com/browse/HAL-1670.
> [HAL-1670] added a test-case for oracle xa urls with parentheses

- resources-subsystem-fixtures/src/main/java/org/jboss/hal/testsuite/fixtures/undertow/ApplicationSecurityDomainFixtures.java
- tests-configuration-ejb/src/test/java/org/jboss/hal/testsuite/test/configuration/ejb/MessageDrivenEJBTest.java
- tests-configuration-ejb/src/test/java/org/jboss/hal/testsuite/test/configuration/ejb/SingletonEJBTest.java
- tests-configuration-ejb/src/test/java/org/jboss/hal/testsuite/test/configuration/ejb/StatefulEJBTest.java
- tests-configuration-ejb/src/test/java/org/jboss/hal/testsuite/test/configuration/ejb/StatelessEJBTest.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/SessionOperationsTest.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/handlers/FileHandlerAttributesTest.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/handlers/FileHandlerTest.java
- tests-hal-basic/src/test/java/org/jboss/hal/testsuite/test/TakeTourTest.java
- tests-hal-deployment/src/test/java/org/jboss/hal/testsuite/test/deployment/DomainContentRepositoryDeploymentTest.java
- tests-hal-deployment/src/test/java/org/jboss/hal/testsuite/test/deployment/DomainServerGroupDeploymentTest.java
- tests-hal-deployment/src/test/java/org/jboss/hal/testsuite/test/deployment/StandaloneDeploymentTest.java
- tests-hal-vulnerabilities/src/test/java/org/jboss/hal/testsuite/test/vulnerability/VulnerabilityTest.java
- tests/keycloak/src/test/java/org/jboss/hal/testsuite/test/keycloak/KeycloakWildflyOperations.java
Fixing `org.jboss.hal.testsuite.test.deployment` -> `deployment` where applicable.
> Removed error which occured during refactoring

- common/src/main/java/org/jboss/hal/testsuite/fragment/finder/ServerPreviewFragment.java
- common/src/main/java/org/jboss/hal/testsuite/fragment/finder/ServerStatusPreviewFragment.java
- tests-hal-runtime/src/test/java/org/jboss/hal/testsuite/test/runtime/ServerStatusTest.java
Test for https://issues.redhat.com/browse/HAL-1729
> HAL-1729: Verify memory in server status preview

- common/src/main/java/org/jboss/hal/testsuite/fragment/TagsInputFragment.java
- resources-subsystem-fixtures/src/main/java/org/jboss/hal/testsuite/fixtures/EJBFixtures.java
- tests-configuration-ejb/src/test/java/org/jboss/hal/testsuite/test/configuration/ejb/ServerInterceptorsTest.java
Tests for https://issues.redhat.com/browse/HAL-1580
> HAL-1580: Add tests for EJB server interceptors

- common/src/main/java/org/jboss/hal/testsuite/page/runtime/StandaloneServerPage.java
- pom.xml
- resources-subsystem-fixtures/src/main/java/org/jboss/hal/testsuite/fixtures/HttpManagementInterfaceFixtures.java
- tests-configuration-management/src/test/java/org/jboss/hal/testsuite/test/configuration/management/ConstantHeadersChecks.java
- tests-configuration-management/src/test/java/org/jboss/hal/testsuite/test/configuration/management/ConstantHeadersHeaderTest.java
- tests-configuration-management/src/test/java/org/jboss/hal/testsuite/test/configuration/management/ConstantHeadersPathTest.java
- tests-configuration-management/src/test/java/org/jboss/hal/testsuite/test/configuration/management/ssl/HttpManagementInterfaceTest.java
Tests for https://issues.redhat.com/browse/HAL-1645
Please note:
This test requires the latest HAL console snapshot: 3.4.0-SNAPSHOT
> HAL-1645: Add tests for constant headers management

- common/src/main/java/org/jboss/hal/testsuite/page/configuration/DistributableWebPage.java
- resources-subsystem-fixtures/src/main/java/org/jboss/hal/testsuite/fixtures/DistributableWebFixtures.java
- tests-configuration-distributableweb/src/test/java/org/jboss/hal/testsuite/test/configuration/distributableweb/InfinispanSessionTest.java
- tests-configuration-messaging/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/server/destinations/JMSTopicTest.java
Test case for https://issues.redhat.com/browse/HAL-1625
> HAL-1625: Add test to pause a JMS topic

- tests-hal-deployment/src/test/java/org/jboss/hal/testsuite/test/deployment/StandaloneDeploymentTest.java
Test for https://issues.redhat.com/browse/HAL-1737
> HAL-1737: Add test method to verify deployment hash

- common/src/main/java/org/jboss/hal/testsuite/fragment/finder/ColumnFragment.java
- tests/rbac/src/test/java/RbacServerGroupsTestCase.java
Test case for https://issues.jboss.org/browse/HAL-1632
Note that since this requires authentication. I was not able to make it work correctly on Safari. It requires adding test:test user to management users.
> Test case for HAL-1632

- common/src/main/java/org/jboss/hal/testsuite/creaper/command/AddKeyManager.java
- common/src/main/java/org/jboss/hal/testsuite/creaper/command/AddKeyStore.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/server/hosts/HttpInvokerTest.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/server/listener/HTTPSListenerSSLTest.java
https://issues.redhat.com/browse/HAL-1758
> HAL-1758: Adjust tests for legacy security removal

- common/src/main/java/org/jboss/hal/testsuite/page/configuration/MessagingServerHaPolicyPage.java
- pom.xml
- tests-configuration-ejb/src/test/java/org/jboss/hal/testsuite/test/configuration/ejb/BeanPoolTest.java
- tests-configuration-messaging/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/server/ha/policy/AbstractHaPolicyTest.java
- tests-configuration-messaging/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/server/ha/policy/FinderTest.java
- tests-configuration-messaging/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/server/ha/policy/ReplicationColocated.java
- tests-configuration-messaging/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/server/ha/policy/ReplicationMasterTest.java
- tests-configuration-messaging/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/server/ha/policy/SharedStoreMasterTest.java
- tests-configuration-messaging/src/test/java/org/jboss/hal/testsuite/test/configuration/messaging/server/ha/policy/ViewTest.java
- tests/keycloak/src/test/java/org/jboss/hal/testsuite/test/keycloak/KeycloakOperations.java
Fixing issues where console left testsuite behind. Fixing https://issues.redhat.com/browse/HAL-1798
TIMEOUT was replaced by SUSPEND_TIMEOUT in https://github.com/hal/console/commit/3b488b31769b10a1fe8e1e4c1e4cb68dd0f6d5f2
> [HAL-1798] HAL compiles again

- tests-configuration-transaction/src/test/java/org/jboss/hal/testsuite/test/configuration/transaction/StatisticsDisplayedTest.java
WIP: This test checks if the display of statistics in Transactions and Undertow runtime sections are displayed as they should be.
> Statistics Displayed Test

- tests-hal-configuration/src/test/java/org/jboss/hal/testsuite/test/configuration/SubsystemsTest.java
https://issues.redhat.com/browse/HAL-1924
jsr77 is no longer part of WildFly/EAP.
> HAL-1924 Fix/migrate tests-hal-configuration component tests of testsuite.next

- tests-hal-runtime/src/test/java/org/jboss/hal/testsuite/test/runtime/ServerStatusTest.java
https://issues.redhat.com/browse/HAL-1943
> HAL-1943 Fix ServerStatusTest in tests-hal-runtime of testsuite.next

- common/src/main/java/org/jboss/hal/testsuite/page/runtime/ManagementOperationsPage.java
https://issues.redhat.com/browse/HAL-1941
> HAL-1941 Cancel button visible for cancelled management operations

- pom.xml
- resources-subsystem-fixtures/src/main/java/org/jboss/hal/testsuite/fixtures/ElytronFixtures.java
- tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/factoriestransformers/AbstractFactoriesTransformersTest.java
- tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/mappers/decoders/role/mapper/MappedRoleMapperTest.java
- tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/other/settings/OtherSettingsTest.java
- tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/other/settings/StoresSettingsTest.java
- tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/ssl/CertificateAuthorityAccountTest.java
https://issues.redhat.com/browse/HAL-1918
> HAL-1918 Fix/migrate tests-configuration-elytron tests of testsuite.next

- common/src/main/java/org/jboss/hal/testsuite/page/configuration/UndertowServerPage.java
- pom.xml
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/SessionOperationsTest.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/application/security/domain/CredentialReferenceTest.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/filters/ExpressionFilterAttributesTest.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/filters/ExpressionFilterTest.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/server/listener/HTTPListenerConfigurationTest.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/server/listener/HTTPSListenerSSLTest.java
- tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/servlet/container/CookiesTest.java
https://issues.redhat.com/browse/HAL-1934
> HAL-1934 Fix/migrate tests-configuration-undertow tests of testsuite.next

- common/src/main/java/org/jboss/hal/testsuite/fragment/HeaderFragment.java
- pom.xml
Triggered by https://issues.redhat.com/browse/HAL-1945 / https://github.com/hal/console/pull/1013
> Update hal.version to 3.6.17.Final
