hal/testsuite.next

tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/deploymentscanner/DeploymentScannerFixtures.java, tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/deploymentscanner/DeploymentScannerTest.java, tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/infinispan/InfinispanFixtures.java, tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/infinispan/LocalCacheTest.java
...when running the whole test cases. See https://github.com/hal/hal.next/issues/159 for more info.
=> Limit resource reusing between tests to avoid false alarms

common/src/main/java/org/jboss/hal/testsuite/fragment/AlertFragment.java, common/src/main/java/org/jboss/hal/testsuite/fragment/finder/FinderPreviewFragment.java, tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/systemproperty/SystemPropertyFixtures.java, tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/systemproperty/SystemPropertyTest.java, tests/basic/src/test/java/org/jboss/hal/testsuite/test/runtime/microprofile/health/MicroProfileHealthCheckTest.java
Upstream issue: https://issues.jboss.org/browse/HAL-1543
EAP7 issue: https://issues.jboss.org/browse/EAP7-1062
Adds a test which selects the micro-profile health check in runtime and checks that the status is successful. Works only for standalone mode.
=> EAP7-1062: Add test for microprofile health check

tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/infinispan/InfinispanFixtures.java, tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/infinispan/cache/container/distributed/cache/DistributedCacheFinderTest.java
HALL issue [https://issues.jboss.org/browse/HAL-1509](https://issues.jboss.org/browse/HAL-1509)
Description
Creation of Distributed Cache on Infinispan subsystem fails with:
"WFLYCTL0369: Required capabilities are not available:
org.wildfly.clustering.infinispan.transport.channel.test-container; Possible registration points for this capability:
/subsystem=infinispan/cache-container=*/transport=jgroups"
Note that it also fails for Invalidation Cache and Replicated Cache. It works for Local Cache
=> [HAL-1509] - Creating a non-local cache container in web console fails

tests/basic/src/test/java/org/jboss/hal/testsuite/test/configuration/datasource/NonXADatasourceCreateTest.java
Issue link: [https://issues.jboss.org/browse/HAL-1570](https://issues.jboss.org/browse/HAL-1570)
Description: The datasource-class attribute is set when the wizard finishes regardless if the user explicitly set the attribute. The datasource-class limits driver functionality and should only be explicitly set by the user.
=> [HAL-1570] - Do not automatically set datasource-class at datasource wizard

common/src/main/java/org/jboss/hal/testsuite/fragment/finder/IOWorkerPreviewFragment.java, tests/basic/src/test/java/org/jboss/hal/testsuite/test/runtime/io/IOWorkerTest.java
Description: WFCORE-3333 exposed a number of busy threads in the task worker thread pool in JBoss CLI. Add the metric under IO Worker Runtime in the management console.
Jira issue:[https://issues.jboss.org/browse/HAL-1576](https://issues.jboss.org/browse/HAL-1576)
=> [Hal 1576] - Add BusyWorkerThreadCount metric in IO WorkerPreview

common/src/main/java/org/jboss/hal/testsuite/fragment/finder/IOWorkerPreviewFragment.java, tests/basic/src/test/java/org/jboss/hal/testsuite/test/runtime/io/IOWorkerTest.java
Description:WFCORE-3333 exposed a number of busy threads in the task worker thread pool in JBoss CLI. Add the metric under IO Worker Runtime in the management console.
Jira issue: [https://issues.jboss.org/browse/HAL-1576](https://issues.jboss.org/browse/HAL-1576)
PR to 72x branch is [https://github.com/hal/testsuite.next/pull/123](https://github.com/hal/testsuite.next/pull/123)
=> [HAL-1576] - Add BusyWorkerThreadCount metric in IO WorkerPreview

tests/basic/src/test/java/org/jboss/hal/testsuite/test/runtime/io/UrlConnectionTestCase.java
Description: If only https is enabled the admin console shows no server url at Runtime -> Hosts -> <Host name> -> <Server name>.
There is a filter for socket bindings with a name started with http in org.jboss.hal.core.runtime.server.ServerUrlTasks which takes the first such binding regardless it is bound (enabled) or not, see [1]. This then leads to n/a at line 128, see [2].
[https://issues.jboss.org/browse/WFLY-12115](https://issues.jboss.org/browse/WFLY-12115)
=> [WFLY-12115] - Console shows server URL as n/a if http is disabled

common/src/main/java/org/jboss/hal/testsuite/page/runtime/elytron/ElytronRuntimeStoresPage.java, tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/ssl/CredentialStoreTest.java
Upstream issue: [HAL-1762 - Aliases are removed from the credential store when passwords are updated from the admin console](https://issues.redhat.com/browse/HAL-1762)
Issue description: Updating the password of an alias within the credential store from the web console using set-secret operation, removes it automatically. This is only replicated if it is done through the web console, not through the CLI.
Link to PR to 7.4.x branch: [https://github.com/hal/testsuite.next/pull/161](https://github.com/hal/testsuite.next/pull/161)
=> [HAL-1762] - Aliases are removed from the credential store when passwords are updated from the admin console

README.md, common/src/main/java/org/jboss/hal/testsuite/category/DomainHcDc.java, common/src/main/java/org/jboss/hal/testsuite/fragment/finder/HostsPreviewFragment.java, common/src/main/java/org/jboss/hal/testsuite/page/runtime/HostsPage.java, pom.xml, tests-configuration-undertow/pom.xml, tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/server/hosts/NoResourceDefinitionTestCase.java
Title: Web Console returning WFLYCTL0030: No resource definition is registered for address
Description:
The trick to reproduce is to have a DC and an and additional HC. This issue is not reproducible when the Undertow -> Deployment tab is reached out from the DC, for example, master HC.
The problem is not on the server-side, it was verified manually that running the operation via CLI works without any issue. It seems a problem derived from how HAL mounts the address to access to Deployment tab when the tab is reached out from the HC which is not the DC.
Jira issue : [https://issues.redhat.com/browse/HAL-1750](https://issues.redhat.com/browse/HAL-1750)
PR to 73x branch [https://github.com/hal/testsuite.next/pull/151](https://github.com/hal/testsuite.next/pull/151)
=> Add test for HAL-1750

README.md, common/src/main/java/org/jboss/hal/testsuite/category/DomainHcDc.java, common/src/main/java/org/jboss/hal/testsuite/fragment/finder/HostsPreviewFragment.java, common/src/main/java/org/jboss/hal/testsuite/page/runtime/HostsPage.java, pom.xml, tests/basic/src/test/java/org/jboss/hal/testsuite/test/runtime/hosts/NoResourceDefinitionTestCase.java
Title: Web Console returning WFLYCTL0030: No resource definition is registered for address
Description:
The trick to reproduce is to have a DC and an and additional HC. This issue is not reproducible when the Undertow -> Deployment tab is reached out from the DC, for example, master HC.
The problem is not on the server-side, it was verified manually that running the operation via CLI works without any issue. It seems a problem derived from how HAL mounts the address to access to Deployment tab when the tab is reached out from the HC which is not the DC.
Jira issue : [https://issues.redhat.com/browse/HAL-1750](https://issues.redhat.com/browse/HAL-1750)
=> [HAL-1750] - Web Console returning WFLYCTL0030: No resource definition is registered for address

tests-hal-runtime/src/test/java/org/jboss/hal/testsuite/test/runtime/ActiveThreadsCountTest.java
Upstream issue:  [HAL-1767 - Add active threads count to batch preview](https://issues.redhat.com/browse/HAL-1767)
Description issue:
Currently, the preview in Runtime / Monitor / Batch shows values for
Active (attribute completed-task-count)
Largest (attribute largest-thread-count)
This issue is about adjusting the semantics and adding a third bar:
Active (attribute active-count)
Current (attribute current-thread-count)
Largest (attribute largest-thread-count)
Link to test run: [https://main-jenkins-csb-eapcpqe.apps.ocp4.prod.psi.redhat.com/job/eap-74x-hal-3-basic-standalone/16/](https://main-jenkins-csb-eapcpqe.apps.ocp4.prod.psi.redhat.com/job/eap-74x-hal-3-basic-standalone/16/)
Link to pull request to branch  7.4.x [https://github.com/hal/testsuite.next/pull/169](https://github.com/hal …
=> [Hal 1767]  - Add test if the preview in Runtime - Monitor - Batch shows values for Current

tests-configuration-infinispan/src/test/java/org/jboss/hal/testsuite/test/configuration/infinispan/cache/container/CacheViewTest.java
[HAL-1757] - Missing metadata: [resource description] @ {selected.profile}/subsystem=infinispan/cache-container=*/distributed-cache=*/memory=binary
Description: When try to view details any type of cache in cache container the following error message appear:
Missing metadata: [resource description] @ {selected.profile}/subsystem=infinispan/cache-container=*/distributed-cache=*/memory=binary
Jira issue: [HAL-1757](https://issues.redhat.com/browse/HAL-1757)
=> Test for HAL-1757

common/pom.xml, pom.xml, tests-configuration-management/pom.xml, tests-configuration-undertow/pom.xml, tests/keycloak/pom.xml
https://issues.redhat.com/browse/HAL-1882
=> HAL-1882: Fix testsuite.next build failure caused by commons-io transitive dependencies

tests-configuration-management/src/test/java/org/jboss/hal/testsuite/test/configuration/management/operations/ManagementOperationsTest.java, tooling-management-operations/src/main/java/org/jboss/hal/testsuite/tooling/management/operations/ManagementOperations.java
https://issues.redhat.com/browse/HAL-1920
There is a wrong assumption in the test that cancelled operations are no longer listed. Such operations can be listed, but should be marked as cancelled. This fix changes the original assumption accordingly.
=> HAL-1920 part 2: Fixing ManagementOperationsTest.cancelNonProgressingOperation

README.md, prepare.sh, shutdown.sh
Add prepare and shutdown scripts
=> Create an easy way to prepare and shutdown server locally

common/src/main/java/org/jboss/hal/testsuite/page/runtime/ManagementOperationsPage.java
Negative IDs usually appears on JDK 17. Tested locally.
=> Fix ManagementOperationsTest#cancelOperation for negative IDs

common/pom.xml, pom.xml, tests-configuration-management/pom.xml, tests-configuration-undertow/pom.xml, tests/keycloak/pom.xml
https://issues.redhat.com/browse/HAL-1882
Backport of https://github.com/hal/testsuite.next/pull/187.
=> HAL-1882: Fix testsuite.next build failure caused by commons-io transitive dependencies (backport from master)

tests-configuration-datasource/src/test/java/org/jboss/hal/testsuite/test/configuration/datasource/DataSourcePoolNameTest.java
Tests that if forward slash separator used in poolName then datasource view at runtime environment works.
=> Add test for HAL-1906

common/src/main/java/org/jboss/hal/testsuite/Console.java, common/src/main/java/org/jboss/hal/testsuite/CrudOperations.java, common/src/main/java/org/jboss/hal/testsuite/Random.java, common/src/main/java/org/jboss/hal/testsuite/fragment/EmptyState.java, common/src/main/java/org/jboss/hal/testsuite/fragment/FormFragment.java, common/src/main/java/org/jboss/hal/testsuite/fragment/TableFragment.java, common/src/main/java/org/jboss/hal/testsuite/fragment/VerticalNavigationFragment.java, common/src/main/java/org/jboss/hal/testsuite/page/BasePage.java, tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/JDBCRealmTest.java, tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/SessionOperationsTest.java, tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/application/security/domain/SingleSignOnAddTest.java, tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/server/listener/AJPListenerConfigurationTest.java, tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/servlet/container/CrawlerTest.java, tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/servlet/container/JSPTest.java, tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/servlet/container/SessionsTest.java, tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/servlet/container/WebSocketsTest.java, tests-hal-runtime/src/test/java/org/jboss/hal/testsuite/test/runtime/OpenPortsTest.java, tests-hal-runtime/src/test/java/org/jboss/hal/testsuite/test/runtime/ServerStatusTest.java
https://issues.redhat.com/browse/HAL-1971
The main aim is to eliminate intermittent failures in elytron and undertow related modules.
=> Hardening against intermittent failures

common/pom.xml, pom.xml, tests/keycloak/pom.xml
https://issues.redhat.com/browse/HAL-1882
Backport of #187
=> HAL-1882: Fix testsuite.next build failure caused by commons-io transitive dependencies (backport)

tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/LdapRealmTest.java, tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/SecurityRealmsTest.java, tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/other/settings/SslSettingsTest.java, tests-configuration-elytron/src/test/java/org/jboss/hal/testsuite/test/configuration/elytron/other/settings/StoresSettingsTest.java
Due to changes in several attribute names in the Add pop-ups (see [comment on JBEAP-29197](https://issues.redhat.com/browse/JBEAP-29197?focusedId=26517104&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26517104)  there are dots added and some of the web console upstream tests related to those forms started to fail.
The affected tests are:
- LdapRealmTest.create
- LdapRealmTest.tryCreate
- SecurityRealmsTest.propertiesRealmCreate
- SecurityRealmsTest.propertiesRealmTryCreate
- SslSettingsTest.keyManagerCreate
- StoresSettingsTest.credentialStoreCreate
- StoresSettingsTest.credentialStoreTryCreate
- StoresSettingsTest.keyStoreCreate
- StoresSettingsTest.keyStoreTryCreate
=> [EAPQE-3195] LdapRealmTest, SecurityRealmsTest, SslSettingsTest and StoresSettingsTest fixed due to the nested attributes changes
